### ISSUE TITLE
Unicode error Windows

### ISSUE THREAD

**Issue by ghost** [scholnicks/itunes-library#4]
Tried to test this code found Unicode error

import os
from itunesLibrary import library

path = os.path.join("F:","/iTunes/iTunes Music Library.xml")

# must first parse...
lib = library.parse(path)

# print len(lib)    # number of items stored

for playlist in lib.playlists:
    for item in playlist.items:
        print(item)          # perform function on each item in the playlist

# get a single playlist
playlist = lib.getPlaylist("Gray")

# get a list of all of the David Bowie songs
bowie_items = lib.getItemsForArtist("David Bowie")

# get a single song
single_song = lib.getItemsById("16116")

# get the iTunes application version
print(lib.applicationVersion)

RESULT:

PS F:\Sandbox> & "C:/Program Files/Python36/python.exe" f:/Sandbox/itunes.py
Traceback (most recent call last):
  File "f:/Sandbox/itunes.py", line 7, in <module>
    lib = library.parse(path)
  File "C:\Program Files\Python36\lib\site-packages\itunesLibrary\library.py", line 14, in parse
    return parser.Parser().parse(pathToXMLFile,ignoreRemoteSongs)
    xml.sax.parse(open(pathToXMLFile,'r'), self)
  File "C:\Program Files\Python36\lib\xml\sax\__init__.py", line 33, in parse
    parser.parse(source)
  File "C:\Program Files\Python36\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Program Files\Python36\lib\xml\sax\xmlreader.py", line 126, in parse
    buffer = file.read(self._bufsize)
  File "C:\Program Files\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 18174: character maps to <undefined>
PS F:\Sandbox> & "C:/Program Files/Python36/python.exe" f:/Sandbox/itunes.py
Traceback (most recent call last):
  File "f:/Sandbox/itunes.py", line 7, in <module>
    lib = library.parse(path)
  File "C:\Program Files\Python36\lib\site-packages\itunesLibrary\library.py", line 14, in parse
    return parser.Parser().parse(pathToXMLFile,ignoreRemoteSongs)
  File "C:\Program Files\Python36\lib\site-packages\itunesLibrary\parser.py", line 43, in parse
    xml.sax.parse(open(pathToXMLFile,'r'), self)
  File "C:\Program Files\Python36\lib\xml\sax\__init__.py", line 33, in parse
    parser.parse(source)
  File "C:\Program Files\Python36\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Program Files\Python36\lib\xml\sax\xmlreader.py", line 126, in parse
    buffer = file.read(self._bufsize)
  File "C:\Program Files\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 18174: character maps to <undefined>

**Comment by JeffKouba** [comment]
I am having exactly the same issue.  Windows 10.

**Comment by apepelis** [comment]
the fix, ituneslibrary\parser.py
change this
    def parse(self,pathToXMLFile,ignoreRemoteSongs):
        """parses the XML file passed in"""
        self.lib = library.Library(ignoreRemoteSongs)
        xml.sax.parse(open(pathToXMLFile,'r'), self)
        return self.lib

to this
    def parse(self,pathToXMLFile,ignoreRemoteSongs):
        """parses the XML file passed in"""
        self.lib = library.Library(ignoreRemoteSongs)
        xml.sax.parse(open(pathToXMLFile,'r', encoding="utf8"), self)
        return self.lib

**Comment by JeffKouba** [comment]
Excellent!  Works great now.  Thanks!!!


Jeff Kouba
jskouba@gmail.com

**Comment by scholnicks** [comment]
Fixed thanks to Thanks to jskouba@gmail.com. I've uploaded 1.1.5 to PyPi
